### Controller for publishing to the joint_states topic

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 125

### Gripper controllers

gripper_controller:
  type: effort_controllers/GripperActionController
  joints:
    - $(arg side)_gripper_joint
  joint: $(arg side)_gripper_joint
  goal_tolerance: 0.01
  stalled_velocity_threshold: 0.01
  stall_timeout: 0.2
  gains:
    $(arg side)_gripper_joint: {p: 100, i: 50, d: 5, i_clamp_min: -50, i_clamp_max: 50}

gripper_torque_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
    - $(arg side)_gripper_joint

### Joint position interface controllers
joint_position_controller:
  type: blue_controllers/BlueJointGroupPositionController
  joints:
    - $(arg side)_base_roll_joint
    - $(arg side)_shoulder_lift_joint
    - $(arg side)_shoulder_roll_joint
    - $(arg side)_elbow_lift_joint
    - $(arg side)_elbow_roll_joint
    - $(arg side)_wrist_lift_joint
    - $(arg side)_wrist_roll_joint
  $(arg side)_base_roll_joint:
    pid: {p: 28, i: 0.0, d: 4, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_shoulder_lift_joint:
    pid: {p: 50, i: 0, d: 3, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_shoulder_roll_joint:
    pid: {p: 50, i: 0, d: 3, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_elbow_lift_joint:
    pid: {p: 50, i: 0, d: 3, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_elbow_roll_joint:
    pid: {p: 50, i: 0, d: 3, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_wrist_lift_joint:
    pid: {p: 15, i: 0, d: 1, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_wrist_roll_joint:
    pid: {p: 15, i: 0, d: 1, i_clamp_min: -1, i_clamp_max: 1}

### Joint effort interface controllers
joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - $(arg side)_base_roll_joint
    - $(arg side)_shoulder_lift_joint
    - $(arg side)_shoulder_roll_joint
    - $(arg side)_elbow_lift_joint
    - $(arg side)_elbow_roll_joint
    - $(arg side)_wrist_lift_joint
    - $(arg side)_wrist_roll_joint
  constraints:
    goal_time: 0.5
    $(arg side)_base_roll_joint:
      trajectory: 0.5
      goal: 0.02
    $(arg side)_shoulder_lift_joint:
      trajectory: 0.5
      goal: 0.02
    $(arg side)_shoulder_roll_joint:
      trajectory: 0.5
      goal: 0.02
    $(arg side)_elbow_lift_joint:
      trajectory: 0.5
      goal: 0.02
    $(arg side)_elbow_roll_joint:
      trajectory: 0.5
      goal: 0.02
    $(arg side)_wrist_lift_joint:
      trajectory: 0.5
      goal: 0.02
    $(arg side)_wrist_roll_joint:
      trajectory: 0.5
      goal: 0.02
  gains:
    $(arg side)_base_roll_joint: {p: 750, i: 150, d: 5, i_clamp_min: -500, i_clamp_max: 500}
    $(arg side)_shoulder_lift_joint: {p: 750, i: 150, d: 5, i_clamp_min: -500, i_clamp_max: 500}
    $(arg side)_shoulder_roll_joint: {p: 750, i: 125, d: 5, i_clamp_min: -500, i_clamp_max: 500}
    $(arg side)_elbow_lift_joint: {p: 750, i: 130, d: 5, i_clamp_min: -500, i_clamp_max: 500}
    $(arg side)_elbow_roll_joint: {p: 750, i: 125, d: 5, i_clamp_min: -500, i_clamp_max: 500}
    $(arg side)_wrist_lift_joint: {p: 750, i: 120, d: 5, i_clamp_min: -500, i_clamp_max: 500}
    $(arg side)_wrist_roll_joint: {p: 750, i: 120, d: 5, i_clamp_min: -500, i_clamp_max: 500}

joint_torque_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
    - $(arg side)_base_roll_joint
    - $(arg side)_shoulder_lift_joint
    - $(arg side)_shoulder_roll_joint
    - $(arg side)_elbow_lift_joint
    - $(arg side)_elbow_roll_joint
    - $(arg side)_wrist_lift_joint
    - $(arg side)_wrist_roll_joint

joint_soft_position_controller:
  type: blue_controllers/BlueJointGroupPositionController
  joints:
    - $(arg side)_base_roll_joint
    - $(arg side)_shoulder_lift_joint
    - $(arg side)_shoulder_roll_joint
    - $(arg side)_elbow_lift_joint
    - $(arg side)_elbow_roll_joint
    - $(arg side)_wrist_lift_joint
    - $(arg side)_wrist_roll_joint
  $(arg side)_base_roll_joint:
    pid: {p: 50, i: 5.0, d: 10, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_shoulder_lift_joint:
    pid: {p: 40, i: 3, d: 10, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_shoulder_roll_joint:
    pid: {p: 40, i: 3, d: 8, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_elbow_lift_joint:
    pid: {p: 30, i: 2, d: 8, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_elbow_roll_joint:
    pid: {p: 30, i: 2, d: 8, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_wrist_lift_joint:
    pid: {p: 20, i: 1, d: 5, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_wrist_roll_joint:
    pid: {p: 15, i: 1, d: 5, i_clamp_min: -1, i_clamp_max: 1}

joint_ctc:
  type: blue_controllers/BlueJointGroupCTC
  ctc_weight: 1.0
  joints:
    - $(arg side)_base_roll_joint
    - $(arg side)_shoulder_lift_joint
    - $(arg side)_shoulder_roll_joint
    - $(arg side)_elbow_lift_joint
    - $(arg side)_elbow_roll_joint
    - $(arg side)_wrist_lift_joint
    - $(arg side)_wrist_roll_joint
  $(arg side)_base_roll_joint:
    pid: {p: 200, i: 0.0, d: 50, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_shoulder_lift_joint:
    pid: {p: 200, i: 0, d: 50, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_shoulder_roll_joint:
    pid: {p: 400, i: 0, d: 70, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_elbow_lift_joint:
    pid: {p: 100, i: 0, d: 50, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_elbow_roll_joint:
    pid: {p: 400, i: 0, d: 70, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_wrist_lift_joint:
    pid: {p: 100, i: 0, d: 50, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_wrist_roll_joint:
    pid: {p: 400, i: 0, d: 50, i_clamp_min: -1, i_clamp_max: 1}
