koko_hardware:
    joint_names: ['lift_joint', 'roll_joint']
    motor_names: ['right_motor', 'left_motor']
    motor_ids: [14, 16]
    gear_ratio: [7.1875, 8.24448529412] # 8.24448529412 results from 7.1875 * (39 / 34) from the output gear
    current_slope: [1.0, 1.0] # 1.0 is decent approx for small motors
    current_offset: [0.0, 0.0]
    calibration_initial_angles: [0.0, 0.0]
    hardstop_start_angles: [-0.23, 0.0] # angles that you the robot is in for hardstop calibration
    directions:        [-1.0, 1.0]
    torque_directions: [-1.0, 1.0]
    joint_torque_directions: [1.0, 1.0]
    calibration_encoder: [4.4834423477927574, 3.5856800916826863] # deprecated
    calibration_joint_vive: [-0.2689415593931021, 0.085327798760949689] #deprecated
    paired_constraints: [0, 1]
    #vive or rviz
    target_mode: "vive"
    hardstop_torque_limit: 0.1
